PREFIX ramon: <http://rdfdata.eionet.europa.eu/ramon/ontology/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
#SELECT DISTINCT ?region ?code ?label
CONSTRUCT { ?eurostat skos:exactMatch ?region }
FROM <http://nuts.geovocab.org/data/0.91/nuts-rdf-0.91.ttl>
FROM NAMED <http://eurostat.linked-statistics.org/dic/geo.rdf>
{
  ?region a ramon:NUTSRegion; ramon:code ?code
  BIND (IRI(CONCAT("http://eurostat.linked-statistics.org/dic/geo#", REPLACE(?code, "GR", "EL"))) AS ?eurostat)
  OPTIONAL { GRAPH <http://eurostat.linked-statistics.org/dic/geo.rdf> { ?eurostat skos:prefLabel ?label } }
}
ORDER BY ?code
