PREFIX ramon-geo: <http://ec.europa.eu/eurostat/ramon/ontologies/geographic.rdf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
#SELECT ?region ?code ?label
CONSTRUCT { ?eurostat skos:exactMatch ?region }
FROM <http://ec.europa.eu/eurostat/ramon/rdfdata/nuts2008.rdf>
FROM <http://eurostat.linked-statistics.org/dic/geo.rdf>
{
  ?region a ramon-geo:NUTSRegion; ramon-geo:regionCode ?code
  BIND (IRI(CONCAT("http://eurostat.linked-statistics.org/dic/geo#", REPLACE(?code, "GR", "EL"))) AS ?eurostat)
  OPTIONAL { ?eurostat skos:prefLabel ?label }
}
ORDER BY ?code
