CREATE TABLE job (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	employer_id INT REFERENCES employer(id),
	contact_id INT REFERENCES contact(id),	
	title_id INT REFERENCES title(id),
	description TEXT,
	unique_id VARCHAR(50),
	source_id INT REFERENCES source(id),
	starting_date DATE,
	ending_date DATE,
	country_code CHAR(2) REFERENCES country(id),
	region_id INT REFERENCES region(id),
	minimum_salary float,
	maximum_salary float,
	salary_comment TEXT,
	salary_currency_id INT REFERENCES salary_currency(id),
	salary_period_id INT REFERENCES salary_period(id),
	salary_tax_id INT REFERENCES salary_tax(id),
	contract_type_id INT REFERENCES contract_type(id),
	contract_hours_id INT REFERENCES contract_hours(id),
	hours_per_week_min float,
	hours_per_week_max float,
	accommodation_provided boolean,
	relocation_covered boolean,
	meals_included boolean,
	travel_expenses boolean,
	professional_qualifications_required boolean,
	education_skills_id INT REFERENCES education_skills(id),
	experience_id INT REFERENCES experience(id),
	driving_license_id INT REFERENCES driving_license(id),
	minimum_age INT,
	maximum_age INT,
	how_to_apply_id INT REFERENCES how_to_apply(id),
	last_date_for_application DATE,
	date_published DATE,
	last_modification_date DATE,
	national_reference VARCHAR(255),
	eures_reference INT,
	nace_code VARCHAR(255),
	isco_code VARCHAR(10) REFERENCES isco(id),
	number_of_posts INT,
	url_search TEXT,
	url TEXT,
	url_scraper_date DATE,
	url_scraper_hour TIME,
	job_scraper_date DATE,
	job_scraper_hour TIME,
	PRIMARY KEY (id),
	UNIQUE (unique_id,source_id)
) DEFAULT CHARACTER SET utf8;
