INSERT INTO source (name, acronym, name_clean, eng, country_code, local_id) VALUES
('EURES Central Database', 'EURES', 'European Employment Services', 'European Employment Services', '', 1),
('AMS, Public Employment Services, Austria', 'AMS', 'Arbeitmarktservice', 'Austrian Public Employment Service', 'AT', 1),
('Pôle Emploi, Public Employment Services, France', 'PE', 'Pôle Emploi', 'Employment center', 'FR', 1),
('Bolzano-Alto Adige/Bozen-Südtirol, Public Employment Services', '', 'Bolzano-Alto Adige/Bozen-Südtirol', '', 'IT', 1),
('AMS, Public Employment Services, Denmark', 'AMS', 'Arbejdsmarkedsstyrelsen', 'Public Employment Service', 'DK', 1),
('VDAB, Public Employment Services, Belgium', 'VDAB', 'Vlaamse Dienst voor Arbeidsbemiddeling en Beroepsopleiding', '', 'BE', 1),
('BA, Public Employment Services, Germany', 'BA', 'Bundesagentur für Arbeit', 'Federal Employment Agency', 'DE', 1),
('YEKA/MLSI, Public Employment Services, Cyprus', 'YEKA', 'Ypourgeio Ergasias kai Koinonikon Asfaliseon', 'Ministry of Labor and Social Insurance', 'CY', 1),
('MPSV, Public Employment Services, Czech Republic', 'MPSV', 'Ministerstvo práce a sociálních věcí', 'Ministry of Labour and Social Affairs', 'CZ', 1),
('OAED, Public Employment Services, Greece', 'OAED', '', 'Greek Manpower Employment Organization', 'GR', 1),
('VMST, Public Employment Services, Iceland', 'VMST', '', '', 'IS', 1),
('Actiris, Public Employment Services, Belgium', 'ACTIRIS', 'Actiris', '', 'BE', 2),
('MOL/Työ- ja elinkeinoministeriö, Public Employment Services, Finland', 'MOL', 'MOL/Työ- ja elinkeinoministeriö', '', 'FI', 1),
('LDB, Public Employment Services, Lithuania', 'LDB', '', '', 'LT', 1),
('ADEM, Public Employment Services, Luxembourg', 'ADEM', '', '', 'LU', 1),
('ETC, Public Employment Services, Malta', 'ETC', '', '', 'MT', 1),
('JOBCENTRE PLUS, Public Employment Services, United Kingdom', 'JCP', 'JobCentre Plus', 'JobCentre Plus', 'UK', 1),
('UWV WERKbedrijf, Public Employment Services, Netherlands', 'UWV', 'UWV WERKbedrijf', '', 'NL', 1),
('NAV, Public Employment Services, Norway', 'NAV', '', '', 'NO', 1),
('PSZ, Public Employment Services, Poland', 'PSZ', '', '', 'PL', 1),
('UPSVAR, Public Employment Services, Slovakia', 'UPSVAR', '', '', 'SK', 1),
('ZRSZ, Public Employment Services, Slovenia', 'ZRSZ', '', '', 'SI', 1),
('Public Employment Service of Spain', 'INEM', 'Instituto Nacional de Empleo', 'National Institute of Employment', 'ES', 1),
('Arbetsförmedlingen, Public Employment Services, Sweden', 'AF', 'Arbetsförmedlingen', '', 'SE', 1),
('SECO, Public Employment Services, Switzerland', 'SECO', '', '', 'CH', 1),
('DEL, Public Employment Services, Northern Ireland', 'DEL', '', '', 'IE', 1);